# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rubycas-client"
  s.version = "2.3.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Zukowski", "Matt Walker", "Matt Campbell"]
  s.date = "2012-06-20"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  s.homepage = "http://github.com/rubycas/rubycas-client"
  s.licenses = ["MIT"]
  s.rdoc_options = ["--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Client library for the Central Authentication Service (CAS) protocol."

  s.add_runtime_dependency 'activesupport', ">= 0"
  s.add_runtime_dependency 'dice_bag', '>= 0.9', '< 2.0'
  s.add_development_dependency 'json', '>= 0'
  s.add_development_dependency 'rspec', '>= 0'
  s.add_development_dependency 'bundler', '>= 1.0'
  s.add_development_dependency 'jeweler', '>= 0'
  s.add_development_dependency 'actionpack', '>= 0'
  s.add_development_dependency 'activerecord', '>= 0'
  s.add_development_dependency 'rake', '>= 0'
  s.add_development_dependency 'simplecov', '>= 0'
  s.add_development_dependency 'guard', '>= 0'
  s.add_development_dependency 'guard-rspec', '>= 0'
  s.add_development_dependency 'database_cleaner', '>= 0'
  s.add_development_dependency 'sqlite3', '>= 0'
end

